feat: Cluster secrets extra
onedr0p/flux-cluster-template pull request #858
Opened 2023-07-18 13:05 UTC by aumer-amr

This allows for adding extra cluster-secrets to your cluster, without any chance of overriding them accidently.
Since ansible will now always check if the file `cluster-secrets-extra.yaml` already exists or no.

2023-07-18 13:05 UTC, aumer-amr commented
Note im deffo not an ansible person, so there are more likely better ways.

2023-07-18 14:43 UTC, onedr0p commented
I have a few ideas / questions

1. How do you feel about `cluster-secrets-user` instead of `cluster-secrets-extra` ? and we could also do a `cluster-settings-user` to supplement this change.

2. I'm also curious if that we need to update the bootstrap task in taskfiles to include these new files?

2023-07-24 18:12 UTC, onedr0p requested changes
Small nits here but overall looking good.

2023-07-24 18:12 UTC, onedr0p commented on .taskfiles/ClusterTasks.yaml
> +      - kubectl apply -f {{.KUBERNETES_DIR}}/flux/vars/cluster-settings-user.yaml
```suggestion
      - sops --decrypt {{.KUBERNETES_DIR}}/flux/vars/cluster-secrets.sops.yaml | kubectl apply -f -
      - sops --decrypt {{.KUBERNETES_DIR}}/flux/vars/cluster-secrets-user.sops.yaml | kubectl apply -f -
      - kubectl apply -f {{.KUBERNETES_DIR}}/flux/vars/cluster-settings.yaml
      - kubectl apply -f {{.KUBERNETES_DIR}}/flux/vars/cluster-settings-user.yaml
```

2023-07-24 18:12 UTC, onedr0p commented on bootstrap/tasks/kubernetes/main.yaml
> +- name: Check if 'cluster-settings-user.yaml' already exists
```suggestion
- name: Check if the cluster user settings file already exists
```

2023-07-24 18:13 UTC, onedr0p commented on .vscode/settings.json
> +    "ansible.python.interpreterPath": "/home/linuxbrew/.linuxbrew/bin/python3",
We should just remove this line, VSCode keeps adding it in and I keep forgetting to remove it.

2023-07-24 18:40 UTC, onedr0p commented on bootstrap/templates/kubernetes/flux/vars/cluster-secrets-user.sops.yaml.j2
> +  name: cluster-secrets-extra
```suggestion
  name: cluster-secrets-user
```

2023-07-24 18:41 UTC, onedr0p commented on bootstrap/templates/kubernetes/flux/apps.yaml.j2
> +        name: cluster-secrets-extra
```suggestion
      - kind: Secret
        name: cluster-secrets-user
      - kind: ConfigMap
        name: cluster-settings-user
```

2023-07-24 18:42 UTC, onedr0p commented on bootstrap/templates/kubernetes/flux/apps.yaml.j2
> +                name: cluster-secrets-extra
```suggestion
              - kind: Secret
                name: cluster-secrets-user
              - kind: ConfigMap
                name: cluster-settings-user
```

2023-07-24 18:42 UTC, onedr0p commented on bootstrap/templates/kubernetes/flux/apps.yaml.j2
> +        name: cluster-settings-user
```suggestion
      - kind: ConfigMap
        name: cluster-settings-user
      - kind: Secret
        name: cluster-secrets-user
```

2023-07-24 18:43 UTC, onedr0p commented on bootstrap/templates/kubernetes/flux/apps.yaml.j2
> +                name: cluster-settings-user
```suggestion
              - kind: ConfigMap
                name: cluster-settings-user
              - kind: Secret
                name: cluster-secrets-user
```

2023-07-24 19:35 UTC, mrueg commented on .vscode/settings.json
> +    "ansible.python.interpreterPath": "/home/linuxbrew/.linuxbrew/bin/python3",
Maybe add  the .vscode directory to .gitignore? Or is there anything in that users would profit from?

2023-07-24 19:55 UTC, aumer-amr commented on .vscode/settings.json
> +    "ansible.python.interpreterPath": "/home/linuxbrew/.linuxbrew/bin/python3",
I don't really think there are benefits from it is it?

2023-07-24 20:04 UTC, onedr0p commented on .vscode/settings.json
> +    "ansible.python.interpreterPath": "/home/linuxbrew/.linuxbrew/bin/python3",
It is kind of useful e.g. `"sops.defaults.ageKeyFile": "age.key"` is required now for the sops age vscode extension

2023-07-24 20:05 UTC, onedr0p commented on bootstrap/tasks/kubernetes/main.yaml
> +    - item.path not is match('cluster-(settings|secrets)-user\.yaml\.j2')
```suggestion
    - item.path not is regex_match('cluster-(settings|secrets)-user\.yaml\.j2')
```

2023-07-24 20:32 UTC, onedr0p approved these changes

2023-07-24 20:32 UTC, merged

2023-07-24 20:34 UTC, aumer-amr commented
🚀